name: ECPAY2 Select deploy environment template

on:
  workflow_call:
  
jobs:
  deploy_release:
    if: ${{ github.ref_name == 'release' }}
    uses: Evolution-Consulting-SAS/devops-workflows/.github/workflows/ECPAY2-deploy-release-template.yml@release
    secrets: inherit
    
  deploy_staging:
    if: ${{ github.ref_name == 'staging' }}
    uses: Evolution-Consulting-SAS/devops-workflows/.github/workflows/ECPAY2-deploy-staging-template.yml@release
    secrets: inherit

 
