name: Deploy Reports MS (Staging)

on:
  push:
    branches:
      - release

jobs:
  call-deploy:
    uses: Evolution-Consulting-SAS/rd_ecpay_reports_ms_v2/.github/workflows/deploy-staging-template.yml@development
    with:
      PROJECT_FOLDER: rd_ecpay_reports_ms_v2
      DOCKER_SERVICE_NAME: reports_v2_service
    secrets: inherit
